on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hour

jobs:
  baking_pull_request:
    name: "Baking PR"
    runs-on: ubuntu-latest
    steps:
      - uses: ngehrsitz/bake-time@process-multiple-matching-checks
        with:
          check-name: "Baking PR"
          delay-hours: 1
